name: tele_kiosk
description: Telemedicine kiosk Flutter app (assignment)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.2.0
  http: ^0.13.6
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  path_provider: ^2.0.14
  firebase_core: ^3.6.0
  firebase_database: ^11.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/